### ISSUE TITLE
CSS variables and blending

### ISSUE THREAD

**Issue by jeremejevs** [jonathantneal/postcss-color-mod-function#12]
It appears that `blend`/`blenda` can't handle CSS variables at the moment:

```css
.foo {
  color: color-mod(blue blend(var(--red) 50%));
  /*                    ^ Expected a valid blend() adjuster */
}
```

Is this by design? Can't tell from the specs :slightly_smiling_face:

**Comment by insonifi** [comment]
if you remove `var()` it works.
But setting this `transformVars` in `postcss.config.css` doesn't work:

```
module.exports = {
        plugins: {
                'postcss-import': {},
                'postcss-preset-env': {
                        stage: 2,
                },
                'postcss-color-mod-function': {
                        transformVars: true,
                }
        },
};

```

That's odd because doc says:

> By default, var() variables will be transformed.

**Comment by jonathantneal** [comment]
It does work, as long as it can find the original variable. See https://github.com/jonathantneal/postcss-color-mod-function#supported-variables.

> By default, `var()` variables will be used if their corresponding Custom Properties are found in a `:root` rule, or if a fallback value is specified.

```pcss
:root {
  --red: #f00;
}

body {
  color: color-mod(blue blend(var(--red) 50%));
}

/* becomes */

:root {
  --red: #f00;
}

body {
	color: rgb(128, 0, 128);
}
```

You can try this yourself at https://preset-env.cssdb.org/playground.

**Comment by jeremejevs** [comment]
@jonathantneal Sorry, it appears I have oversimplified the original example, didn't test it. It does work when either of the colors are hardcoded, but it doesn't when both are variables:

```css
:root {
  --red: #f2777a;
  --blue: #6699cc;
}

.foo {
  color: color-mod(var(--blue) blend(var(--red) 50%));
}
```

**Comment by jonathantneal** [comment]
@JamesTheHacker, in your case, do you need to wrap your variable?

```css
.luxbar-item a:hover {
  background: color-mod(var(--hot-pink) lightness(60%));
}
```
