### ISSUE TITLE
Contrast color adjuster does not work as expected

### ISSUE THREAD

**Issue by monospaced** [jonathantneal/postcss-color-mod-function#13]
Test case:  https://github.com/monospaced/post-css-color-mod-function-contrast-test

```
$ git clone git@github.com:monospaced/post-css-color-mod-function-contrast-test.git
$ cd post-css-color-mod-function-contrast-test
$ yarn start
```

The resulting CSS in [styles.processed.css](https://github.com/monospaced/post-css-color-mod-function-contrast-test/blob/master/styles.processed.css) does not match my understanding of the [contrast-adjuster spec](https://www.w3.org/TR/css-color-4/#contrast-adjuster) (or the behaviour in postcss-color-function).

For example, I would expect

```css
.maxContrastOnWhite {
  background-color: rgb(255, 255, 255);
  color: color-mod(rgb(255, 255, 255) contrast(100%));
}
```

to be transpiled to

```css
.maxContrastOnWhite {
  background-color: rgb(255, 255, 255);
  color: rgb(0, 0, 0);
}
```

rather than

```css
.maxContrastOnWhite {
  background-color: rgb(255, 255, 255);
  color: rgb(255, 255, 255);
}
```
