### ISSUE TITLE
Duplicate Properties When Variables Used

### ISSUE THREAD

**Issue by jherdman** [jonathantneal/postcss-color-mod-function#33]
Given:

```css

:root {
  --c-reg: rgb(255, 55, 1);
}

.mySelector {
  background-color: color-mod(var(--c-red) lightness(20%));
}
```

Expected:

```css
/* I'm assuming the math this plugin is doing is correct... */

.mySelector {
  background-color: background-color: hsl(12.755905511811026, 100%, 20%);
}
```

Actual:

```css
.mySelector {
  background-color: background-color: hsl(12.755905511811026, 100%, 20%);
  background-color: background-color: hsl(12.755905511811026, 100%, 20%);
}
```

**Comment by jherdman** [comment]
Interestingly I sometimes see...

```css
.mySelector {
  color: rgb(255, 55, 1);
  color: var(--c-red);
}
```
